import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://ycaiusoyqoeccmmixgrf.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYWl1c295cW9lY2NtbWl4Z3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzIzMTgsImV4cCI6MjA4NzE0ODMxOH0.uj4lXNqc88XP8drTvxlwhswxK18sJtRRoVs8JIRTEvI";

export const supabase = createClient(https://ycaiusoyqoeccmmixgrf.supabase.co, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYWl1c295cW9lY2NtbWl4Z3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzIzMTgsImV4cCI6MjA4NzE0ODMxOH0.uj4lXNqc88XP8drTvxlwhswxK18sJtRRoVs8JIRTEvI);