// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycaiusoyqoeccmmixgrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYWl1c295cW9lY2NtbWl4Z3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzIzMTgsImV4cCI6MjA4NzE0ODMxOH0.uj4lXNqc88XP8drTvxlwhswxK18sJtRRoVs8JIRTEvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});